import fs from "fs";
import path from "path";
import { ConcernWithDetails, Intervention } from "@shared/schema";

interface HTMLReportOptions {
  includeLetterhead?: boolean;
  theme?: 'default' | 'professional' | 'minimal';
}

export async function generateConcernHTMLReport(
  concern: ConcernWithDetails,
  interventions: Intervention[],
  outputPath: string,
  options: HTMLReportOptions = {}
): Promise<void> {
  const { theme = 'professional', includeLetterhead = true } = options;
  
  const currentDate = new Date().toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric'
  });

  const concernTypes = Array.isArray(concern.concernTypes) ? concern.concernTypes : [];
  const concernTypeText = concernTypes.length > 0 ? concernTypes.join(', ') : 'Not specified';

  // Format interventions content
  const formattedInterventions = interventions.map(intervention => 
    formatMarkdownToHTML(intervention.description)
  ).join('<div class="section-break"></div>');

  const htmlContent = `
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Student Concern Report - ${concern.studentFirstName} ${concern.studentLastInitial}</title>
    <style>
        ${getReportCSS(theme)}
    </style>
</head>
<body>
    <div class="report-container">
        <!-- Header -->
        <header class="report-header">
            <div class="header-content">
                <h1 class="app-title">Concern2Care</h1>
                <h2 class="report-title">Student Concern Report</h2>
                <p class="report-date">Generated on ${currentDate}</p>
            </div>
            ${includeLetterhead ? '<div class="letterhead-space"></div>' : ''}
        </header>

        <!-- Print Controls (hidden during print) -->
        <div class="print-controls no-print">
            <button 
                onclick="window.print()" 
                class="print-button"
                data-testid="button-print-report"
            >
                <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
                    <polyline points="6,9 6,2 18,2 18,9"></polyline>
                    <path d="M6,18H4a2,2 0 01-2-2V11a2,2 0 012-2H20a2,2 0 012,2v5a2,2 0 01-2,2H18"></path>
                    <polyline points="6,14 18,14"></polyline>
                </svg>
                Print Report
            </button>
        </div>

        <!-- Student Information Section -->
        <section class="info-section">
            <h3 class="section-title">Student Information</h3>
            <div class="info-grid">
                <div class="info-item">
                    <span class="info-label">Name:</span>
                    <span class="info-value">${concern.studentFirstName} ${concern.studentLastInitial}.</span>
                </div>
                <div class="info-item">
                    <span class="info-label">Teacher:</span>
                    <span class="info-value">${concern.teacher.firstName} ${concern.teacher.lastName}</span>
                </div>
                <div class="info-item">
                    <span class="info-label">School:</span>
                    <span class="info-value">${concern.teacher.school || 'Not specified'}</span>
                </div>
            </div>
        </section>

        <!-- Concern Details Section -->
        <section class="concern-section">
            <h3 class="section-title">Concern Details</h3>
            <div class="concern-grid">
                <div class="concern-item">
                    <span class="concern-label">Type:</span>
                    <span class="concern-value">${concernTypeText}</span>
                </div>
                <div class="concern-item">
                    <span class="concern-label">Date Documented:</span>
                    <span class="concern-value">${concern.createdAt?.toLocaleDateString('en-US') || 'Unknown'}</span>
                </div>
            </div>
            
            <div class="description-section">
                <h4 class="description-title">Description:</h4>
                <div class="description-content">
                    ${concern.description || 'No description provided'}
                </div>
            </div>
        </section>

        <!-- AI-Generated Interventions Section -->
        <section class="interventions-section">
            <h3 class="section-title">AI-Generated Intervention Strategies</h3>
            <div class="interventions-content">
                ${formattedInterventions}
            </div>
        </section>

        <!-- Footer -->
        <footer class="report-footer">
            <div class="footer-content">
                <p class="footer-text">
                    This report was generated by Concern2Care. All intervention strategies are evidence-based 
                    and appropriate for Tier 2 implementation.
                </p>
            </div>
        </footer>
    </div>

    <!-- Print styles -->
    <style media="print">
        ${getPrintCSS()}
    </style>
</body>
</html>`;

  // Write the HTML file
  await fs.promises.writeFile(outputPath, htmlContent, 'utf8');
}

function formatMarkdownToHTML(markdown: string): string {
  if (!markdown) return '';

  let html = markdown
    // Headers
    .replace(/^### \*\*(.*?)\*\*/gm, '<h3 class="intervention-title">$1</h3>')
    .replace(/^## \*\*(.*?)\*\*/gm, '<h2 class="major-heading">$1</h2>')
    .replace(/^# \*\*(.*?)\*\*/gm, '<h1 class="main-heading">$1</h1>')
    
    // Sub-headers
    .replace(/^\*\*([^:*]+):\*\*/gm, '<h4 class="sub-heading">$1:</h4>')
    .replace(/^\*\*([^*]+)\*\*/gm, '<h4 class="bold-heading">$1</h4>')
    
    // Bold text
    .replace(/\*\*(.*?)\*\*/g, '<strong>$1</strong>')
    
    // Bullet points (nested)
    .replace(/^    [-*] (.*)/gm, '<li class="nested-bullet">$1</li>')
    .replace(/^  [-*] (.*)/gm, '<li class="sub-bullet">$1</li>')
    .replace(/^[-*] (.*)/gm, '<li class="main-bullet">$1</li>')
    
    // Line breaks
    .replace(/\n\n/g, '</p><p>')
    .replace(/\n/g, '<br>');

  // Wrap in paragraphs
  html = '<p>' + html + '</p>';
  
  // Clean up empty paragraphs
  html = html.replace(/<p><\/p>/g, '').replace(/<p><br><\/p>/g, '');
  
  // Convert bullet lists
  html = html.replace(/(<li class="[^"]*">.*?<\/li>)/g, (match) => {
    return '<ul class="intervention-list">' + match + '</ul>';
  });

  return html;
}

function getReportCSS(theme: string): string {
  const baseStyles = `
    * {
        margin: 0;
        padding: 0;
        box-sizing: border-box;
    }

    body {
        font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
        line-height: 1.6;
        color: #333;
        background: #f8fafc;
    }

    .report-container {
        max-width: 210mm;
        margin: 0 auto;
        background: white;
        box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1);
        min-height: 297mm;
    }

    .report-header {
        background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
        color: white;
        padding: 2rem;
        text-align: center;
    }

    .app-title {
        font-size: 2.5rem;
        font-weight: 700;
        margin-bottom: 0.5rem;
        text-shadow: 0 2px 4px rgba(0,0,0,0.3);
    }

    .report-title {
        font-size: 1.5rem;
        font-weight: 400;
        margin-bottom: 1rem;
        opacity: 0.9;
    }

    .report-date {
        font-size: 0.9rem;
        opacity: 0.8;
    }

    .section-title {
        color: #2563eb;
        font-size: 1.4rem;
        font-weight: 600;
        margin-bottom: 1rem;
        padding-bottom: 0.5rem;
        border-bottom: 2px solid #e2e8f0;
    }

    .info-section, .concern-section, .interventions-section {
        padding: 2rem;
        border-bottom: 1px solid #e2e8f0;
    }

    .info-grid, .concern-grid {
        display: grid;
        grid-template-columns: repeat(auto-fit, minmax(250px, 1fr));
        gap: 1rem;
        margin-bottom: 1.5rem;
    }

    .info-item, .concern-item {
        background: #f8fafc;
        padding: 1rem;
        border-radius: 8px;
        border-left: 4px solid #3b82f6;
    }

    .info-label, .concern-label {
        font-weight: 600;
        color: #374151;
        display: block;
        margin-bottom: 0.25rem;
    }

    .info-value, .concern-value {
        color: #1f2937;
        font-size: 1.1rem;
    }

    .description-section {
        margin-top: 1.5rem;
    }

    .description-title {
        font-size: 1.1rem;
        font-weight: 600;
        color: #374151;
        margin-bottom: 0.75rem;
    }

    .description-content {
        background: #f9fafb;
        padding: 1.5rem;
        border-radius: 8px;
        border: 1px solid #e5e7eb;
        line-height: 1.7;
    }

    .interventions-content {
        background: #fefefe;
        padding: 2rem;
        border-radius: 12px;
        border: 1px solid #e2e8f0;
    }

    .intervention-title {
        color: #1e40af;
        font-size: 1.3rem;
        font-weight: 600;
        margin: 1.5rem 0 1rem 0;
        padding: 0.5rem 0;
        border-bottom: 1px solid #e2e8f0;
    }

    .major-heading {
        color: #1e40af;
        font-size: 1.2rem;
        font-weight: 600;
        margin: 1.25rem 0 0.75rem 0;
    }

    .sub-heading {
        color: #7c3aed;
        font-size: 1.1rem;
        font-weight: 500;
        margin: 1rem 0 0.5rem 0;
    }

    .bold-heading {
        color: #374151;
        font-size: 1rem;
        font-weight: 600;
        margin: 0.75rem 0 0.5rem 0;
    }

    .intervention-list {
        margin: 0.75rem 0 1rem 1.5rem;
        padding-left: 0;
    }

    .main-bullet {
        list-style: none;
        position: relative;
        margin: 0.5rem 0;
        padding-left: 1.5rem;
        color: #374151;
    }

    .main-bullet::before {
        content: "•";
        color: #3b82f6;
        font-weight: bold;
        position: absolute;
        left: 0;
    }

    .sub-bullet {
        list-style: none;
        position: relative;
        margin: 0.25rem 0 0.25rem 1rem;
        padding-left: 1.5rem;
        color: #6b7280;
        font-size: 0.95rem;
    }

    .sub-bullet::before {
        content: "◦";
        color: #6b7280;
        position: absolute;
        left: 0;
    }

    .nested-bullet {
        list-style: none;
        position: relative;
        margin: 0.25rem 0 0.25rem 2rem;
        padding-left: 1.5rem;
        color: #9ca3af;
        font-size: 0.9rem;
    }

    .nested-bullet::before {
        content: "▪";
        color: #9ca3af;
        position: absolute;
        left: 0;
    }

    .section-break {
        height: 2rem;
        border-bottom: 1px solid #f3f4f6;
        margin: 2rem 0;
    }

    .print-controls {
        position: sticky;
        top: 0;
        background: white;
        border-bottom: 1px solid #e2e8f0;
        padding: 1rem 2rem;
        text-align: right;
        z-index: 10;
        box-shadow: 0 2px 4px rgba(0,0,0,0.1);
    }

    .print-button {
        display: inline-flex;
        align-items: center;
        gap: 0.5rem;
        background: #3b82f6;
        color: white;
        border: none;
        padding: 0.75rem 1.5rem;
        border-radius: 8px;
        font-size: 0.9rem;
        font-weight: 500;
        cursor: pointer;
        transition: all 0.2s ease;
        box-shadow: 0 2px 4px rgba(59, 130, 246, 0.2);
    }

    .print-button:hover {
        background: #2563eb;
        transform: translateY(-1px);
        box-shadow: 0 4px 8px rgba(59, 130, 246, 0.3);
    }

    .print-button:active {
        transform: translateY(0);
    }

    .report-footer {
        background: #f8fafc;
        padding: 2rem;
        text-align: center;
        border-top: 1px solid #e2e8f0;
    }

    .footer-text {
        color: #6b7280;
        font-size: 0.9rem;
        font-style: italic;
        line-height: 1.5;
    }
  `;

  return baseStyles;
}

function getPrintCSS(): string {
  return `
    body {
        background: white !important;
    }

    .report-container {
        box-shadow: none !important;
        max-width: none !important;
        margin: 0 !important;
    }

    .report-header {
        background: #667eea !important;
        -webkit-print-color-adjust: exact !important;
        print-color-adjust: exact !important;
    }

    .print-controls,
    .no-print {
        display: none !important;
    }

    @page {
        margin: 1cm;
        size: A4;
    }

    .section-break {
        page-break-before: avoid;
        break-inside: avoid;
    }

    .intervention-title,
    .major-heading {
        break-after: avoid;
        page-break-after: avoid;
    }
  `;
}